stages:
  - build
  - tests

build:
  image: ${CI_REGISTRY}/dockers/ci/centos-build:8
  stage: build
  before_script:
    - dnf install -y openssl-devel
  script:
    - make
  artifacts:
    expire_in: 2 days
    paths:
      - leek

tests:
  image: ${CI_REGISTRY}/dockers/ci/centos-build:8
  stage: tests
  dependencies:
    - build
  before_script:
    - dnf install -y python3-pyasn1 python3-pyasn1-modules
  script:
    - ./leek --verbose --stop --output=output/ --duration 60s --prefix gitlab
    - python tests/checker.py output/*
