stages:
  - build
  - tests


centos7-build:
  image: ${CI_REGISTRY}/dockers/ci/centos-build:7
  stage: build
  cache:
    key: "centos7"
    paths:
      - cache/yum
  before_script:
    - yum --setopt=cachedir=cache/yum install -y openssl-devel
  script:
    - bash autogen.sh
    - ./configure
    - make rpm
  artifacts:
    expire_in: 2 days
    paths:
      - _build/RPMS/x86_64/*.rpm

centos7-tests:
  image: ${CI_REGISTRY}/dockers/ci/centos-build:7
  stage: tests
  cache:
    key: "centos7"
    paths:
      - cache/yum
  needs:
    - centos7-build
  before_script:
    - yum install -y _build/RPMS/x86_64/*.rpm
    - yum --setopt=cachedir=cache/yum install -y python2-pyasn1 python2-pyasn1-modules
  script:
    - leek --verbose --stop --output=output/ --duration 60s --prefix gitlab
    - python tests/checker.py output/*

centos8-build:
  image: ${CI_REGISTRY}/dockers/ci/centos-build:8
  stage: build
  cache:
    key: "centos8"
    paths:
      - cache/dnf
  before_script:
    - dnf --setopt=cachedir=cache/dnf install -y openssl-devel
  script:
    - bash autogen.sh
    - ./configure
    - make rpm
  artifacts:
    expire_in: 2 days
    paths:
      - _build/RPMS/x86_64/*.rpm

centos8-tests:
  image: ${CI_REGISTRY}/dockers/ci/centos-build:8
  stage: tests
  cache:
    key: "centos8"
    paths:
      - cache/dnf
  needs:
    - centos8-build
  before_script:
    - dnf install -y _build/RPMS/x86_64/*.rpm
    - dnf --setopt=cachedir=cache/dnf install -y python3-pyasn1 python3-pyasn1-modules
  script:
    - leek --verbose --stop --output=output/ --duration 60s --prefix gitlab
    - python tests/checker.py output/*

debian10-build:
  image: ${CI_REGISTRY}/dockers/ci/debian-build:10
  stage: build
  cache:
    key: "debian10"
    paths:
      - cache/aptdeb
  before_script:
    - mkdir --parents cache/aptdeb
    - apt-get update --yes
    - apt-get -o dir::cache::archives="${PWD}/cache/aptdeb" install -y libssl-dev
  script:
    - bash autogen.sh
    - ./configure
    - make deb
  artifacts:
    expire_in: 2 days
    paths:
      - _build/DEBIAN/leek_*.deb
      - _build/DEBIAN/leek-*.deb

debian10-tests:
  image: ${CI_REGISTRY}/dockers/ci/debian-build:10
  stage: tests
  cache:
    key: "debian10"
    paths:
      - cache/aptdeb
  needs:
    - debian10-build
  before_script:
    - mkdir --parents cache/aptdeb
    - apt-get update --yes
    - dpkg -i _build/DEBIAN/leek_*.deb
    - apt-get -o dir::cache::archives="${PWD}/cache/aptdeb" install -y python3-pyasn1 python3-pyasn1-modules
  script:
    - leek --verbose --stop --output=output/ --duration 60s --prefix gitlab
    - python3 tests/checker.py output/*

debian11-build:
  image: ${CI_REGISTRY}/dockers/ci/debian-build:11
  stage: build
  cache:
    key: "debian11"
    paths:
      - cache/aptdeb
  before_script:
    - mkdir --parents cache/aptdeb
    - apt-get update --yes
    - apt-get -o dir::cache::archives="${PWD}/cache/aptdeb" install -y libssl-dev
  script:
    - bash autogen.sh
    - ./configure
    - make deb
  artifacts:
    expire_in: 2 days
    paths:
      - _build/DEBIAN/leek_*.deb
      - _build/DEBIAN/leek-*.deb

debian11-tests:
  image: ${CI_REGISTRY}/dockers/ci/debian-build:11
  stage: tests
  cache:
    key: "debian11"
    paths:
      - cache/aptdeb
  needs:
    - debian11-build
  before_script:
    - mkdir --parents cache/aptdeb
    - apt-get update --yes
    - dpkg -i _build/DEBIAN/leek_*.deb
    - apt-get -o dir::cache::archives="${PWD}/cache/aptdeb" install -y python3-pyasn1 python3-pyasn1-modules
  script:
    - leek --verbose --stop --output=output/ --duration 60s --prefix gitlab
    - python3 tests/checker.py output/*

ubuntu2004-build:
  image: ${CI_REGISTRY}/dockers/ci/ubuntu-build:20.04
  stage: build
  cache:
    key: "ubuntu2004"
    paths:
      - cache/aptubn
  before_script:
    - mkdir --parents cache/aptubn
    - apt-get update --yes
    - apt-get -o dir::cache::archives="${PWD}/cache/aptubn" install -y libssl-dev
  script:
    - bash autogen.sh
    - ./configure
    - make deb
  artifacts:
    expire_in: 2 days
    paths:
      - _build/DEBIAN/leek_*.deb
      - _build/DEBIAN/leek-*.ddeb

ubuntu2004-tests:
  image: ${CI_REGISTRY}/dockers/ci/ubuntu-build:20.04
  stage: tests
  cache:
    key: "ubuntu2004"
    paths:
      - cache/aptubn
  needs:
    - ubuntu2004-build
  before_script:
    - mkdir --parents cache/aptubn
    - apt-get update --yes
    - dpkg -i _build/DEBIAN/leek_*.deb
    - apt-get -o dir::cache::archives="${PWD}/cache/aptubn" install -y python3-pyasn1 python3-pyasn1-modules
  script:
    - leek --verbose --stop --output=output/ --duration 60s --prefix gitlab
    - python3 tests/checker.py output/*

ubuntu2204-build:
  image: ${CI_REGISTRY}/dockers/ci/ubuntu-build:22.04
  stage: build
  cache:
    key: "ubuntu2204"
    paths:
      - cache/aptubn
  before_script:
    - mkdir --parents cache/aptubn
    - apt-get update --yes
    - apt-get -o dir::cache::archives="${PWD}/cache/aptubn" install -y libssl-dev
  script:
    - bash autogen.sh
    - ./configure
    - make deb
  artifacts:
    expire_in: 2 days
    paths:
      - _build/DEBIAN/leek_*.deb
      - _build/DEBIAN/leek-*.ddeb

ubuntu2204-tests:
  image: ${CI_REGISTRY}/dockers/ci/ubuntu-build:22.04
  stage: tests
  cache:
    key: "ubuntu2204"
    paths:
      - cache/aptubn
  needs:
    - ubuntu2004-build
  before_script:
    - mkdir --parents cache/aptubn
    - apt-get update --yes
    - dpkg -i _build/DEBIAN/leek_*.deb
    - apt-get -o dir::cache::archives="${PWD}/cache/aptubn" install -y python3-pyasn1 python3-pyasn1-modules
  script:
    - leek --verbose --stop --output=output/ --duration 60s --prefix gitlab
    - python3 tests/checker.py output/*
