language: c
dist: trusty
sudo: required
group: travis_latest
matrix:
  # GCC based compilation.
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - libssl-dev
            - gcc-5
      env:
        - MATRIX_EVAL="CC=gcc-5"
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - libssl-dev
            - gcc-6
      env:
        - MATRIX_EVAL="CC=gcc-6"
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - libssl-dev
            - gcc-7
      env:
        - MATRIX_EVAL="CC=gcc-7"

    # CLANG based compilation.
    - os: linux
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-3.9
          packages:
            - libssl-dev
            - clang-3.9
      env:
        - MATRIX_EVAL="CC=clang-3.9"
    - os: linux
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-4.0
          packages:
            - libssl-dev
            - clang-4.0
      env:
        - MATRIX_EVAL="CC=clang-4.0"
    - os: linux
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-5.0
          packages:
            - libssl-dev
            - clang-5.0
      env:
        - MATRIX_EVAL="CC=clang-5.0"
before_script:
  - eval "${MATRIX_EVAL}"
  - ${CC} --version
  - wget 'https://launchpad.net/~ubuntu-toolchain-r/+archive/ubuntu/test/+files/binutils_2.27-9ubuntu1_amd64.deb'
  - sudo dpkg -i binutils_2.27-9ubuntu1_amd64.deb
  - as --version
script:
  - make
  - ./leek --help
  - ./leek --stop --duration 60s --verbose --prefix travis
