language: c
dist: xenial
sudo: required
group: travis_latest
matrix:
  # GCC based compilation.
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - libssl-dev
            - gcc-5
      env:
        - MATRIX_EVAL="CC=gcc-5"
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - libssl-dev
            - gcc-6
      env:
        - MATRIX_EVAL="CC=gcc-6"
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - libssl-dev
            - gcc-7
      env:
        - MATRIX_EVAL="CC=gcc-7"
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - libssl-dev
            - gcc-8
      env:
        - MATRIX_EVAL="CC=gcc-8"


    # CLANG based compilation.
    - os: linux
      addons:
        apt:
          sources:
            - llvm-toolchain-xenial-4.0
          packages:
            - libssl-dev
            - clang-4.0
      env:
        - MATRIX_EVAL="CC=clang-4.0"
    - os: linux
      addons:
        apt:
          sources:
            - llvm-toolchain-xenial-5.0
          packages:
            - libssl-dev
            - clang-5.0
      env:
        - MATRIX_EVAL="CC=clang-5.0"
    - os: linux
      addons:
        apt:
          sources:
            - llvm-toolchain-xenial-6.0
          packages:
            - libssl-dev
            - clang-6.0
      env:
        - MATRIX_EVAL="CC=clang-6.0"
before_script:
  - eval "${MATRIX_EVAL}"
  - ${CC} --version
  - as --version
script:
  - make
  - ./leek --help
  - ./leek --stop --duration 60s --verbose --prefix travis
