language: c
dist: trusty
sudo: required
group: travis_latest
matrix:
  include:
    - os: linux
      addons:
        apt:
          packages:
            - libssl-dev
      env:
        - MATRIX_EVAL="CC=gcc"
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - libssl-dev
            - gcc-5
      env:
        - MATRIX_EVAL="CC=gcc-5"
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - libssl-dev
            - gcc-6
      env:
        - MATRIX_EVAL="CC=gcc-6"
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - libssl-dev
            - gcc-7
      env:
        - MATRIX_EVAL="CC=gcc-7"
before_script:
  - eval "${MATRIX_EVAL}"
  - ${CC} --version
  - wget 'https://launchpad.net/~ubuntu-toolchain-r/+archive/ubuntu/test/+files/binutils_2.27-9ubuntu1_amd64.deb'
  - sudo dpkg -i binutils_2.27-9ubuntu1_amd64.deb
  - as --version
script:
  - make
  - ./src/leek --help
  - ./src/leek --benchmark --stop --verbose --prefix travis
